### ISSUE TITLE
Package conflicts with roave/security-advisories

### ISSUE THREAD

**Issue by leonardfischer** [phpseclib/phpseclib2_compat#13]
Hi,

similar to #11 the roave/security-advisories package marked versions of phpseclib lower than 3.0.34 as a conflict ([see here](https://github.com/Roave/SecurityAdvisories/commit/89f6e236e9317263c8ffa1d7d32cb6828b12aea0)). Because the compatibility package identifies itself as providing version 2.0.41, it now is in conflict and composer fails installing.

Or is this (like in the previous ticket) an issue on [Roave/SecurityAdvisories](https://github.com/Roave/SecurityAdvisories) side?

Best regards
Leo

**Comment by terrafrost** [comment]
The CVE (which I didn't create) says the affected version is for < 3.0.34 - not >= 3.0.0 < 3.0.34. Because there's no lower bound on the versions affected the only way a new release of the 2.0 branch could resolve the issue is if I released 2.0.42 as 4.0.0 or as 3.0.35. Which I am absolutely not going to do. The former is terrible because new major releases ought to actually be improvements - not regressions. And releasing the 2.0 branch as 3.0.35 would be a huuuuge BC break to anyone using the 3.0 branch.

Anyway, I contacted the creator of the CVE and they said they had submitted the update. I gather from the last time this happened that this just takes time. Like a person manually reviews each CVE update request before it's actually made official. So at this point it's just a waiting game. But, unlike last time and because of the affected versions string that they used, the fix for last time won't work this time.

And as for Roave/SecurityAdvisories...  I gather they just build the list automatically from the CVEs. Which really suggests to me that the CVE process is fundamentally flawed. Like what happens if someone submits a bogus CVE that makes it through their not-so-great screening process that says all versions are affected? You could use the whole CVE workflow to DoS entire development environments.

**Comment by leonardfischer** [comment]
Hey @terrafrost,

first of all: thank you for taking the time to check this! I really appreciate it! I believe in the long run we will have to migrate fully to `phpseclib/phpseclib:^3`.

I also think it's a bit alarming that any "not-properly-checked" CVE can land in that list and potentially break a lot of applications or at least make a lot of DEVs sweat :/ 

Anyway - I'll join the waiting game for this one :)

**Comment by terrafrost** [comment]
I created https://github.com/Roave/SecurityAdvisories/issues/123 . Even despite the CVE being updated [Roave/SecurityAdvisories](https://github.com/Roave/SecurityAdvisories) has not been updated...

**Comment by leonardfischer** [comment]
Hey @terrafrost I believe it was updated :)

The new "conflict" states `phpseclib/phpseclib: <2.0.31|>=3,<3.0.34` - I can update my packages again!

Thank you for your support - I'll close the ticket :)
